### ISSUE TITLE
Awesome Design 2.0 draft

### ISSUE THREAD

**Issue by gztchan** [gztchan/awesome-design#82]
## Todos

- [ ] Re-generate sections of the list, which help readers locate what they seek for more quickly
- [ ] Update resources, including adding new ones and remove ones not good enough
- [ ] Provide abstract for each resource
